void registry();
void unregistry();
bool read();
void lexing();
void stmt();
void eval();
void declare();
void declare_void();
double val(const std::string& t);
double evaluate(size_t begin, size_t end);
bool valid_name(const std::string& t);
void error(const std::string& msg);